// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package visit

import mock "github.com/stretchr/testify/mock"

// MockVisitRepositorier is an autogenerated mock type for the VisitRepositorier type
type MockVisitRepositorier struct {
	mock.Mock
}

// FindAll provides a mock function with given fields:
func (_m *MockVisitRepositorier) FindAll() ([]Visit, error) {
	ret := _m.Called()

	var r0 []Visit
	if rf, ok := ret.Get(0).(func() []Visit); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Visit)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindById provides a mock function with given fields: id
func (_m *MockVisitRepositorier) FindById(id int) (*Visit, error) {
	ret := _m.Called(id)

	var r0 *Visit
	if rf, ok := ret.Get(0).(func(int) *Visit); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Visit)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
