definitions:
  info.Info:
    properties:
      appName:
        type: string
      description:
        type: string
      version:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /info:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/info.Info'
      summary: Show app info
      tags:
      - Info
swagger: "2.0"
