// Code generated by mockery v2.42.2. DO NOT EDIT.

package health

import mock "github.com/stretchr/testify/mock"

// MockCheckServicer is an autogenerated mock type for the CheckServicer type
type MockCheckServicer struct {
	mock.Mock
}

type MockCheckServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCheckServicer) EXPECT() *MockCheckServicer_Expecter {
	return &MockCheckServicer_Expecter{mock: &_m.Mock}
}

// check provides a mock function with given fields:
func (_m *MockCheckServicer) check() (*Check, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for check")
	}

	var r0 *Check
	var r1 error
	if rf, ok := ret.Get(0).(func() (*Check, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *Check); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Check)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCheckServicer_check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'check'
type MockCheckServicer_check_Call struct {
	*mock.Call
}

// check is a helper method to define mock.On call
func (_e *MockCheckServicer_Expecter) check() *MockCheckServicer_check_Call {
	return &MockCheckServicer_check_Call{Call: _e.mock.On("check")}
}

func (_c *MockCheckServicer_check_Call) Run(run func()) *MockCheckServicer_check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCheckServicer_check_Call) Return(_a0 *Check, _a1 error) *MockCheckServicer_check_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCheckServicer_check_Call) RunAndReturn(run func() (*Check, error)) *MockCheckServicer_check_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCheckServicer creates a new instance of MockCheckServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCheckServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCheckServicer {
	mock := &MockCheckServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
